// <auto-generated />
using ITDR.ShoppingCenter.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ITDR.ShoppingCenter.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ITDR.ShoppingCenter.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Misterije",
                            Description = "Upravljanje karakterom i pokusaj da se nadje izlaz iz lavirinta.",
                            ImageURL = "https://localhost:7279/images/glow-in-the-dark.jpg",
                            Name = "Glow In The Dark",
                            Price = 750.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Akcija, Ratne",
                            Description = "Call Of Duty MWII je najprodavanija ratna igrica u kojoj se resavaju misije iz doba 2010.",
                            ImageURL = "https://localhost:7279/images/cod-mw-2.jpg",
                            Name = "Call Of Duty - Modern Warfare II",
                            Price = 1250.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Akcija",
                            Description = "U ulozi Kratosa prelazite teske misije.",
                            ImageURL = "https://localhost:7279/images/god-of-war.jpg",
                            Name = "God Of War",
                            Price = 1100.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Akcija, Misterija",
                            Description = "Witcher, bestseler!",
                            ImageURL = "https://localhost:7279/images/witcher.jpg",
                            Name = "Witcher",
                            Price = 1350.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
